<?php  
//Comprobante
$Comprobante_Version;
$Comprobante_Serie;
$Comprobante_Folio;
$Comprobante_Fecha;
$Comprobante_FormaPago;
$Comprobante_NoCertificado;
$Comprobante_CondicionesDePago;
$Comprobante_SubTotal;
$Comprobante_Descuento;
$Comprobante_Moneda;
$Comprobante_TipoCambio;
$Comprobante_Total;
$Comprobante_TipoDeComprobante;
$Comprobante_MetodoPago;
$Comprobante_LugarExpedicion;
$Comprobante_Sello;
$Comprobante_Certificado;
//Emisor
$Emisor_Rfc;
$Emisor_Nombre;
$Emisor_RegimenFiscal;
//Receptor
$Receptor_Rfc;
$Receptor_Nombre;
$Receptor_UsoCFDI;
//Impuestos
$Impuestos_TotalImpuestosRetenidos;
$Impuestos_TotalImpuestosTrasladados;
//Traslado
$Traslado_Impuesto;
$Traslado_TipoFactor;
$Traslado_TasaOCuota;
$Traslado_Importe;
//TimbreFiscalDigital
$tfd_Version;
$tfd_UUID;
$tfd_FechaTimbrado;
$tfd_RfcProvCertif;
$tfd_SelloCFD;
$tfd_NoCertificadoSAT;
$tfd_SelloSAT;
//catalogos
$Emisor_RegimenFiscal_catalogo;
$Receptor_UsoCFDI_catalogo;
$Comprobante_FormaPago_catalogo;
$Comprobante_TipoDeComprobante_catalogo;
$Comprobante_MetodoPago_catalogo;
//Numero con letra 
$Comprobante_Total_letra;
//rutas de guardado
$codigoQR;
$archivoXML;
$logo;
$logo_factuwin="xmls/imagenes/FACTUWIN.png";
$logo_nomiwin="xmls/imagenes/NOMINWIN.png";
//nomina//
//Nomina
$nomina_Version;
$nomina_FechaPago;
$nomina_FechaInicialPago;
$nomina_FechaFinalPago;
$nomina_NumDiasPagados;
$nomina_TipoNomina;
$nomina_TotalDeduccione;
$nomina_TotalOtrosPagos;
$nomina_TotalPercepciones;
//Emisor
$nomina_Emisor_RegistroPatronal;
//Receptor
$nomina_Receptor_Curp;
$nomina_Receptor_TipoContrato;
$nomina_Receptor_TipoRegimen;
$nomina_Receptor_NumEmpleado;
$nomina_Receptor_PeriodicidadPago;
$nomina_Receptor_ClaveEntFed;
$nomina_Receptor_NumSeguridadSocial;
$nomina_Receptor_Banco;
$nomina_Receptor_FechaInicioRelLaboral;
$nomina_Receptor_Antigüedad;
$nomina_Receptor_Puesto;
$nomina_Receptor_SalarioBaseCotApor;
$nomina_Receptor_RiesgoPuesto;
$nomina_Receptor_SalarioDiarioIntegrado;
//Percepciones
$nombre_nodo="Percepciones";
$nomina_Percepciones_TotalGravado;
$nomina_Percepciones_TotalExento;
$nomina_Percepciones_TotalSueldos;
//Deducciones
$nombre_nodo="Deducciones";
$nomina_Deducciones_TotalOtrasDeducciones;
$nomina_Deducciones_TotalImpuestosRetenidos;
?>
